# reference sim config for actuated cylinder
dynamics_config:
  _target_: planning_through_contact.planning.planar.planar_plan_config.SliderPusherSystemConfig
  pusher_radius: 0.015
  friction_coeff_table_slider: 0.5
  friction_coeff_slider_pusher: 0.1
  grav_acc: 9.81
  integration_constant: 0.3
  force_scale: 0.01
slider_type: 'box'
arbitrary_shape_pickle_path: null
arbitrary_shape_visual_mesh_path: null # Can be null (collision mesh will be used)
arbitrary_shape_rgba: [0.15, 0.15, 0.15, 1.0]
physical_properties: # Slider physical properties
  _target_: planning_through_contact.tools.utils.PhysicalProperties
  mass: 0.1
  inertia: [[1e-5, 0.0, 0.0], [0.0, 1e-5, 0.0], [0.0, 0.0, 1e-5]]
  center_of_mass: null # [0.0, 0.0, 0.0] # Use null for uniform densit7y
  is_compliant: true
  hydroelastic_modulus: 1.0e6
  # NOTE: These friction coefficients are used for sim while the ones in `dynamic_config` are used for planning!
  mu_dynamic: 0.5
  mu_static: 0.5
  mesh_resolution_hint: 0.01
contact_model: ContactModel.kHydroelastic
visualize_desired: true
slider_goal_pose: # Configures the goal pose of the slider
  _target_: planning_through_contact.geometry.planar.planar_pose.PlanarPose
  x: 0.5
  y: 0.0
  theta: 0.0
pusher_start_pose: # Confiures the starting and ending location of the pusher
  _target_: planning_through_contact.geometry.planar.planar_pose.PlanarPose
  x: 0.5
  y: 0.25
  theta: 0.0
time_step: 0.001
closed_loop: false
draw_frames: true
use_realtime: false
delay_before_execution: 5.0
save_plots: false
# TODO: fix this
diffusion_policy_config:
  _target_: planning_through_contact.simulation.controllers.diffusion_policy_source.DiffusionPolicyConfig
  checkpoint: '/home/adam/workspace/gcs-diffusion/data/outputs/push_box_v5/checkpoints/latest.ckpt'
  initial_pusher_pose: ${pusher_start_pose}
  target_slider_pose: ${slider_goal_pose}
  diffusion_policy_path: '/home/adam/workspace/gcs-diffusion'
  freq: 10.0
  delay: ${delay_before_execution}
  debug: false
  device: 'cuda:0'
  cfg_overrides:
    n_action_steps: 8
domain_randomization_color_range: 0.0
use_hardware: false
pusher_z_offset: 0.0125
camera_configs:
  - name: 'overhead_camera'
    orientation:
      roll: 3.141592653589793
      pitch: 0.0
      yaw: 0.0    
    position: [0.5, 0.0, 1.0]
    width: 96
    height: 96
    show_rgb: false
    randomize: false
log_dir: 'diffusion_policy_logs'
multi_run_config:
  _target_: planning_through_contact.simulation.planar_pushing.planar_pushing_sim_config.MultiRunConfig
  num_runs: 2
  max_attempt_duration: 60
  seed: 0
  slider_type: ${slider_type}
  arbitrary_shape_pickle_path: ${arbitrary_shape_pickle_path}
  pusher_start_pose: ${pusher_start_pose}
  slider_goal_pose: ${slider_goal_pose}
  workspace_width: 0.35
  workspace_height: 0.5
  trans_tol: 0.01
  rot_tol: 1.5 # degrees
  evaluate_final_pusher_position: true
  evaluate_final_slider_rotation: true

## Robot specific configs
# sim_config
scene_directive_name: 'planar_pushing_cylinder_plant_hydroelastic.yaml'
default_joint_positions:
  - {pusher_start_pose.x}
  - {pusher_start_pose.y}

# position controller / robot station
robot_station:
  _target_: planning_through_contact.simulation.controllers.cylinder_actuated_station.CylinderActuatedStation
  sim_config: null  # override in hydra.utils.instantiate
  meshcat: null     # override in hydra.utils.instantiate

## Data Collection Config
data_collection_config:
  _target_: planning_through_contact.simulation.environments.data_collection_table_environment.DataCollectionConfig
  generate_plans: false    # Configures whether new plans should be generated
  render_plans: true      # Configures whether plans should be replayed and rendered
  convert_to_zarr: true   # Configures whether the rendered plans should be converted to zarr
  convert_to_zarr_reduce: false # Supercloud flag to perform "reduce" step, leave as false
  plans_dir: 'trajectories/sim_box_data_val' # Save directory for trajectories
  rendered_plans_dir: 'trajectories_rendered/sim_box_data' # Save directory for rendered trajectories
  zarr_path: trajectories_rendered/sim_box_data.zarr # Save directory for zarr dataset
  policy_freq: 10.0
  state_chunk_length: 1024
  action_chunk_length: 2048
  target_chunk_length: 1024
  image_chunk_length: 128
  image_width: 96
  image_height: 96
  plan_config:
    _target_: planning_through_contact.simulation.environments.data_collection_table_environment.PlanConfig
    slider_type: ${slider_type}
    arbitrary_shape_pickle_path: ${arbitrary_shape_pickle_path}
    pusher_radius: 0.015
    contact_lam_min: 0.2
    contact_lam_max: 0.8
    distance_to_object_socp: 0.25
    width: 0.75  # Width of the workspace
    height: 0.5 # Height of the workspace
    center:
      - ${slider_goal_pose.x}
      - ${slider_goal_pose.y}
    buffer: 0.0
    seed: 0     # Seed for data generation
    num_plans: 25 # Number of initial conditions to plan from
    pusher_start_pose: ${pusher_start_pose}
    slider_goal_pose: ${slider_goal_pose}
    limit_rotations: false
    noise_final_pose: false
    num_unique_plans: 2 # Number of plans per initial condition
    sort_plans: true    # Configures whether plans should be sorted and by optimality

  ## Supercloud
  LLSUB_RANK: null
  LLSUB_SIZE: null
