# sim config for the real iiwa set up
dynamics_config:
  _target_: planning_through_contact.planning.planar.planar_plan_config.SliderPusherSystemConfig
  pusher_radius: 0.015
  friction_coeff_table_slider: 0.5
  friction_coeff_slider_pusher: 0.1
  grav_acc: 9.81
  integration_constant: 0.3
  force_scale: 0.01
slider_type: 'arbitrary'
arbitrary_shape_pickle_path: arbitrary_shape_pickles/small_t_pusher.pkl
arbitrary_shape_rgba: [0.15, 0.15, 0.15, 1.0]
arbitrary_shape_visual_mesh_path: null # Can be null (collision mesh will be used)
physical_properties: # Slider physical properties
  _target_: planning_through_contact.tools.utils.PhysicalProperties
  mass: 0.1
  inertia: [[1e-5, 0.0, 0.0], [0.0, 1e-5, 0.0], [0.0, 0.0, 1e-5]]
  center_of_mass: [0.0, -0.0055, 0.0] # Use null for uniform density
  is_compliant: true
  hydroelastic_modulus: 1.0e6
  # NOTE: These friction coefficients are used for sim while the ones in `dynamic_config` are used for planning!
  mu_dynamic: 0.5
  mu_static: 0.5
  mesh_resolution_hint: 0.01
contact_model: ContactModel.kHydroelastic
visualize_desired: true
slider_goal_pose:
  _target_: planning_through_contact.geometry.planar.planar_pose.PlanarPose
  x: 0.587
  y: -0.0355
  theta: 0.0
pusher_start_pose:
  _target_: planning_through_contact.geometry.planar.planar_pose.PlanarPose
  x: 0.587
  y: 0.15
  theta: 0.0
time_step: 0.001
closed_loop: false # MPC flag
draw_frames: true
use_realtime: true
delay_before_execution: 2.0
save_plots: false
gamepad:
  translation_scale: 5.75e-5
  deadzone: 0.01
  gamepad_orientation:
    - [1, 0]
    - [0, -1] # requires reflection (not SO(3))
diffusion_policy_config:
  _target_: planning_through_contact.simulation.controllers.diffusion_policy_source.DiffusionPolicyConfig
  checkpoint: '/home/adam/workspace/gcs-diffusion/data/outputs/sim_sim/baseline_carbon/150/checkpoints/latest.ckpt'
  initial_pusher_pose: ${pusher_start_pose}
  target_slider_pose: ${slider_goal_pose}
  diffusion_policy_path: '/home/adam/workspace/gcs-diffusion'
  freq: 10.0
  delay: 1.0
  debug: false
  device: 'cuda:0'
  cfg_overrides:
    n_action_steps: 8
use_hardware: false
pusher_z_offset: 0.015
camera_configs:
  - name: 'overhead_camera'
    orientation: # slghtly different
      roll: -2.55
      pitch: -0.035
      yaw: 1.5462387054402587
    position: [0.91, -0.075, 0.45] # slightly different
    width: 640
    height: 480
    center_x: 318.05
    center_y: 244.107
    focal_x: 616.704
    focal_y: 616.777
    background:
      r: 0.55
      g: 0.45
      b: 0.35
      a: 1.0
    lights:
      - direction: [0.5, 0, 1]
        color: [1.0, 0.98, 0.957]
        intensity: 0.5
      - direction: [-0.5, 0, 1]
        color: [1.0, 0.98, 0.957]
        intensity: 0.5
    cast_shadows: true
    show_rgb: false
    randomize: false
  - name: 'wrist_camera'
    parent_frame: 'iiwa_link_7'
    orientation:
      roll: 0.2
      pitch: 0.0
      yaw: 1.5707
    position:
      - -0.0825
      - -0.024
      - 0.0575
    width: 640
    height: 480
    center_x: 318.05
    center_y: 244.107
    focal_x: 616.704
    focal_y: 616.777
    light_direction: [0.25, -1.0, 1.75]
    cast_shadows: false
    background:
      r: 0.47
      g: 0.39
      b: 0.27
      a: 1.0
    show_rgb: false
    randomize: false
domain_randomization_color_range: 0.0
log_dir: 'diffusion_policy_logs'
multi_run_config:
  _target_: planning_through_contact.simulation.planar_pushing.planar_pushing_sim_config.MultiRunConfig
  num_runs: 100
  max_attempt_duration: 75
  seed: 0
  slider_type: ${slider_type}
  arbitrary_shape_pickle_path: ${arbitrary_shape_pickle_path}
  pusher_start_pose: ${pusher_start_pose}
  slider_goal_pose: ${slider_goal_pose}
  workspace_width: 0.4
  workspace_height: 0.3
  trans_tol: 0.015 # tol for pusher is 1.5x higher
  rot_tol: 3.5 # degrees
  evaluate_final_pusher_position: true
  evaluate_final_slider_rotation: true
  success_criteria: 'tolerance'
  dataset_path: /home/adam/workspace/gcs-diffusion/data/planar_pushing_cotrain/sim_sim_tee_data.zarr
  slider_physical_properties: ${physical_properties}
  pre_compute_initial_conditions: false
  num_trials_to_record: 20

## Robot specific configs
# sim_config
scene_directive_name: 'planar_pushing_iiwa_plant_hydroelastic.yaml'
default_joint_positions: [0.6202, 1.0135, -0.5873, -1.4182, 0.6449, 0.8986, 2.98796]

# position controller / robot station
robot_station:
  _target_: planning_through_contact.simulation.controllers.iiwa_hardware_station.IiwaHardwareStation
  sim_config: null  # override in hydra.utils.instantiate
  meshcat: null     # override in hydra.utils.instantiate
joint_velocity_limit_factor: 1.0 # .inf

## Data Collection Config
data_collection_config:
  _target_: planning_through_contact.simulation.environments.data_collection_table_environment.DataCollectionConfig
  generate_plans: false
  render_plans: false
  convert_to_zarr: true
  convert_to_zarr_reduce: false # Supercloud flag to perform "reduce" step
  plans_dir: '/home/adam/workspace/planning-through-contact/trajectories/physics_shift_level_1/run_0'
  rendered_plans_dir: '/home/adam/workspace/planning-through-contact/trajectories_rendered/physics_shift_level_1_no_visual_gap'
  zarr_path: '/home/adam/workspace/gcs-diffusion/data/planar_pushing_cotrain/physics_shift/physics_shift_level_1_no_visual_gap.zarr'
  policy_freq: 10.0
  state_chunk_length: 1024
  action_chunk_length: 2048
  target_chunk_length: 1024
  image_chunk_length: 128
  image_width: 128
  image_height: 128
  plan_config:
    _target_: planning_through_contact.simulation.environments.data_collection_table_environment.PlanConfig
    slider_type: ${slider_type}
    arbitrary_shape_pickle_path: ${arbitrary_shape_pickle_path}
    pusher_radius: 0.015
    contact_lam_min: 0.2
    contact_lam_max: 0.8
    distance_to_object_socp: 0.25
    ang_velocity_regularization: 25 # null
    width: 0.35
    height: 0.5
    center:
      - ${slider_goal_pose.x}
      - ${slider_goal_pose.y}
    buffer: 0.0
    seed: 1
    num_plans: 750
    pusher_start_pose: ${pusher_start_pose}
    slider_goal_pose: ${slider_goal_pose}
    limit_rotations: false
    noise_final_pose: true
    num_unique_plans: 2
    sort_plans: true
  ## Supercloud
  LLSUB_RANK: null
  LLSUB_SIZE: null